package execptionhandling;

public class Exception1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
		System.out.print(10/0);}
		catch(ArithmeticException e)
		{
			
		}
		finally
		{
			System.out.println("sanjeev kumar");
			System.out.println("sanjeev rameshwaram is in a good lcation");
		}
	}

}
